In [1]:
import re

CHAPTER_TITLE_DE = "2.1 Definition und Konzepte des Dynamic Pricing im stationären Einzelhandel"
CHAPTER_TEXT_DE = """
Die theoretischen Grundlagen des Dynamic Pricing werden detailliert beschrieben.
Es wird erläutert, wie Dynamic Pricing im Einzelhandel funktioniert und welche unterschiedlichen Ansätze es gibt,
z. B. zeitabhängige Preise oder an die Nachfrage gekoppelte Preisänderungen.
Es wird nicht auf operative Details der Preisgestaltung oder spezifische Implementierungsstrategien eingegangen.
Der Online-Handel wird explizit ausgeklammert.
""".strip()

# Simple, explicit English scope translation (we'll automate DE/EN later)
CHAPTER_SCOPE_EN = (
    "Conceptual and theoretical foundations of dynamic pricing in brick-and-mortar (in-store/offline) retail. "
    "Explain mechanisms and approaches (e.g., time-dependent pricing, demand-linked price changes). "
    "Do not focus on operational implementation details; focus on definitions, concepts, and approaches."
)

def normalize_query(q: str) -> str:
    q = q.lower()
    q = re.sub(r"[^a-z0-9\s\"-]", " ", q)
    q = re.sub(r"\s+", " ", q).strip()
    return q

# Query variants: 1 broad + multiple focused (no hard exclusions yet)
QUERIES = {
    "broad": normalize_query(
        'dynamic pricing definition concepts brick-and-mortar retail in-store offline retail'
    ),
    "theory_foundations": normalize_query(
        'dynamic pricing theory conceptual framework retail'
    ),
    "time_based": normalize_query(
        'time-based pricing time-dependent pricing dynamic pricing retail store'
    ),
    "demand_based": normalize_query(
        'demand-based pricing demand-driven pricing dynamic pricing retail store'
    ),
    "revenue_management": normalize_query(
        'revenue management pricing retail dynamic pricing in-store'
    ),
    "price_discrimination": normalize_query(
        'price discrimination dynamic pricing retail store'
    ),
}

QUERY_LIST = list(QUERIES.values())

print("Chapter (EN scope):", CHAPTER_SCOPE_EN)
print("\nQueries:")
for k, v in QUERIES.items():
    print(f"- {k}: {v}")

Chapter (EN scope): Conceptual and theoretical foundations of dynamic pricing in brick-and-mortar (in-store/offline) retail. Explain mechanisms and approaches (e.g., time-dependent pricing, demand-linked price changes). Do not focus on operational implementation details; focus on definitions, concepts, and approaches.

Queries:
- broad: dynamic pricing definition concepts brick-and-mortar retail in-store offline retail
- theory_foundations: dynamic pricing theory conceptual framework retail
- time_based: time-based pricing time-dependent pricing dynamic pricing retail store
- demand_based: demand-based pricing demand-driven pricing dynamic pricing retail store
- revenue_management: revenue management pricing retail dynamic pricing in-store
- price_discrimination: price discrimination dynamic pricing retail store

# OpenAlex (Works) — broad scholarly coverage (articles/books/chapters)

In [4]:
import os
import time
import requests
import pandas as pd
from typing import Any, Dict, List, Optional

OPENALEX_API_KEY = os.getenv("OPENALEX_API_KEY", "WOZ9qphHIT86mmH5BQFKuB")  # get one at openalex.org/settings/api
if not OPENALEX_API_KEY:
    raise RuntimeError("Set OPENALEX_API_KEY env var.")

BASE_URL = "https://api.openalex.org/works"

PER_PAGE = 100              # up to 200; with abstracts, 50-100 is usually safer
MAX_WORKS_PER_QUERY = 400   # set None to fetch "all" (can be a lot)
TIMEOUT_SEC = 30

OUTPUT_CSV_PATH = "openalex_works.csv"

# ----------------------------
# Helpers
# ----------------------------
def abstract_from_inverted_index(inv: Optional[Dict[str, List[int]]]) -> Optional[str]:
    """
    OpenAlex returns abstracts as abstract_inverted_index: {word: [pos1, pos2, ...]}.
    This reconstructs a best-effort plaintext abstract.
    """
    if not inv:
        return None

    pairs: List[tuple[int, str]] = []
    for word, positions in inv.items():
        if not positions:
            continue
        for p in positions:
            if isinstance(p, int):
                pairs.append((p, word))

    if not pairs:
        return None

    pairs.sort(key=lambda x: x[0])
    max_pos = pairs[-1][0]
    words = [""] * (max_pos + 1)
    for pos, w in pairs:
        if 0 <= pos <= max_pos:
            words[pos] = w

    text = " ".join(w for w in words if w).strip()
    return text or None


def venue_from_primary_location(work: Dict[str, Any]) -> Optional[str]:
    pl = work.get("primary_location") or {}
    src = pl.get("source") or {}
    return src.get("display_name")


def first_n_authors(work: Dict[str, Any], n: int = 6) -> str:
    authors = []
    for a in (work.get("authorships") or [])[:n]:
        name = ((a.get("author") or {}).get("display_name"))
        if name:
            authors.append(name)
    return "; ".join(authors)


def request_with_retries(
    url: str,
    params: Dict[str, Any],
    timeout: int = 30,
    max_retries: int = 5
) -> requests.Response:
    """
    Retries on transient errors (429, 5xx).
    """
    backoff = 1.0
    for attempt in range(1, max_retries + 1):
        r = requests.get(url, params=params, timeout=timeout)

        if r.status_code in (429, 500, 502, 503, 504):
            if attempt == max_retries:
                raise RuntimeError(f"OpenAlex error {r.status_code}\nURL: {r.url}\nBody: {r.text}")
            time.sleep(backoff)
            backoff *= 2
            continue

        if r.status_code >= 400:
            raise RuntimeError(f"OpenAlex error {r.status_code}\nURL: {r.url}\nBody: {r.text}")

        return r

    raise RuntimeError("Unexpected retry loop exit")


def fetch_works_for_query(q: str, max_works: Optional[int]) -> List[Dict[str, Any]]:
    """
    Fetches works for a query using cursor-based pagination.
    """
    rows: List[Dict[str, Any]] = []
    cursor = "*"

    select = (
        "id,display_name,publication_year,type,doi,cited_by_count,"
        "authorships,primary_location,abstract_inverted_index"
    )

    while cursor:
        params = {
            "search": q,
            "per-page": PER_PAGE,
            "cursor": cursor,
            "select": select,
            "api_key": OPENALEX_API_KEY,
        }

        r = request_with_retries(BASE_URL, params=params, timeout=TIMEOUT_SEC)
        data = r.json()

        for w in data.get("results", []) or []:
            rows.append({
                "query": q,
                "title": w.get("display_name"),
                "year": w.get("publication_year"),
                "type": w.get("type"),
                "venue": venue_from_primary_location(w),
                "cited_by": w.get("cited_by_count"),
                "authors(first6)": first_n_authors(w, n=6),
                "doi": w.get("doi"),
                "openalex_id": w.get("id"),
                "abstract": abstract_from_inverted_index(w.get("abstract_inverted_index")),
            })

            if max_works is not None and len(rows) >= max_works:
                return rows

        cursor = (data.get("meta") or {}).get("next_cursor")
        if not cursor:
            break

    return rows


# ----------------------------
# Run
# ----------------------------
all_rows: List[Dict[str, Any]] = []
for q in QUERY_LIST:
    all_rows.extend(fetch_works_for_query(q, max_works=MAX_WORKS_PER_QUERY))

df_openalex = pd.DataFrame(all_rows)

# De-dupe (OpenAlex ID is best unique key; DOI/title as backup)
if not df_openalex.empty:
    df_openalex = df_openalex.drop_duplicates(
        subset=["openalex_id", "doi", "title"],
        keep="first"
    ).reset_index(drop=True)

# Save to CSV
df_openalex.to_csv(OUTPUT_CSV_PATH, index=False, encoding="utf-8")
print(f"Saved {len(df_openalex):,} works to: {OUTPUT_CSV_PATH}")

df_openalex.head(50)

Saved 1,625 works to: openalex_works.csv

,query,title,year,type,venue,cited_by,authors(first6),doi,openalex_id,abstract
0,dynamic pricing definition concepts brick-and-...,Digital Transformation: An Overview of the Cur...,2021,article,SAGE Open,1044,Sascha Kraus; Paul Jones; Norbert Kailer; Alex...,https://doi.org/10.1177/21582440211047576,https://openalex.org/W3202582446,The increasing digitalization of economies has...
1,dynamic pricing definition concepts brick-and-...,Metaverse marketing: How the metaverse will sh...,2022,article,Psychology and Marketing,755,Yogesh K. Dwivedi; Laurie Hughes; Yichuan Wang...,https://doi.org/10.1002/mar.21767,https://openalex.org/W4313310852,Abstract The initial hype and fanfare from the...
2,dynamic pricing definition concepts brick-and-...,Consumer-driven e-commerce,2018,article,International Journal of Physical Distribution...,332,Stanley Frederick W.T. Lim; Xin Jin; Jagjit Si...,https://doi.org/10.1108/ijpdlm-02-2017-0081,https://openalex.org/W2579462724,Purpose The purpose of this paper is to re-exa...
3,dynamic pricing definition concepts brick-and-...,"The Evolution of Social Commerce: The People, ...",2012,article,Communications of the Association for Informat...,533,Chingning Wang; Ping Zhang,https://doi.org/10.17705/1cais.03105,https://openalex.org/W191206311,Social commerce is a form of commerce mediated...
4,dynamic pricing definition concepts brick-and-...,"Exploring Factors That Affect Usefulness, Ease...",2015,article,International Journal of Management & Informat...,299,Yoon C. Cho; Esen Sagynov,https://doi.org/10.19030/ijmis.v19i1.9086,https://openalex.org/W1548690256,Various studies have examined the effects of f...
5,dynamic pricing definition concepts brick-and-...,A Review of Impulse Buying Behavior,2013,review,International Journal of Marketing Studies,320,Ravi Shankar Bhakat; G. Muruganantham,https://doi.org/10.5539/ijms.v5n3p149,https://openalex.org/W2101151549,Researchers and Practitioners have been intere...
6,dynamic pricing definition concepts brick-and-...,A review of the environmental implications of ...,2015,review,International Journal of Physical Distribution...,236,Riccardo Mangiaracina; Gino Marchet; Sara Pero...,https://doi.org/10.1108/ijpdlm-06-2014-0133,https://openalex.org/W2165069623,Purpose – Given the importance of logistics op...
7,dynamic pricing definition concepts brick-and-...,Amazon's Antitrust Paradox,2017,article,Yale Law School Legal Scholarship Repository,205,Lina Khan,None,https://openalex.org/W3122148702,Amazon is the titan of twenty-first century co...
8,dynamic pricing definition concepts brick-and-...,Sustainable Online Shopping Logistics for Cust...,2019,article,Sustainability,113,Daeheon Choi; Chune Young Chung; Jason Young,https://doi.org/10.3390/su11205626,https://openalex.org/W2979639440,This study examines the impact of the quality ...
9,dynamic pricing definition concepts brick-and-...,To immerse or not? Experimenting with two virt...,2017,article,Information Technology and People,163,Savvas Papagiannidis; Eleonora Pantano; Eric W...,https://doi.org/10.1108/itp-03-2015-0069,https://openalex.org/W2311676256,Purpose The purpose of this paper is to examin...
10,dynamic pricing definition concepts brick-and-...,An experimental study to investigate the impac...,2016,article,Journal of Retailing and Consumer Services,106,Emma Beuckels; Liselot Hudders,https://doi.org/10.1016/j.jretconser.2016.08.014,https://openalex.org/W2515315541,None
11,dynamic pricing definition concepts brick-and-...,The New Paradigm of the Omnichannel Retailing:...,2017,article,International Journal of Business and Management,75,Simone Aiolfi; Edoardo Sabbadin,https://doi.org/10.5539/ijbm.v13n1p85,https://openalex.org/W2779829103,"The rise of the Internet, mobile technologies ..."
12,dynamic pricing definition concepts brick-and-...,More Amazon Effects: Online Competition and Pr...,2018,preprint,None,91,Alberto Cavallo,https://doi.org/10.3386/w25138,https://openalex.org/W2895399789,"I study how online competition, with its algor..."
13,dynamic pricing definition concepts brick-and-...,Quality of channel integration and customer lo...,2021,article,Journal of Retailing and Consumer Services,138,Mengjia Gao; Lin Huang,https://doi.org/10.1016/j.jretconser.2021.102688,https://openalex.org/W3189223373,None
14,dynamic pricing definition concepts brick-and-...,Omnichannel retailing and post-pandemic recove...,2022,article,International Journal of Retail & Distribution...,81,Giada Salvietti; Cristina Ziliani; Christoph T...,https://doi.org/10.1108/ijrdm-10-2021-0485,https://openalex.org/W4214679741,Purpose The study aims to propose a comprehens...
15,dynamic pricing definition concepts brick-and-...,Implementing E-Commerce from Logistic Perspect...,2022,article,Sustainability,86,Ilenia Zennaro; Serena Finco; Martina Calzavar...,https://doi.org/10.3390/su14020911,https://openalex.org/W4205541554,E-commerce is always more diffused as a sellin...
16,dynamic pricing definition concepts brick-and-...,Achieving Resilience and Business Sustainabili...,2021,article,Sustainability,104,Matteo Trabucco; Pietro De Giovanni,https://doi.org/10.3390/su132212369,https://openalex.org/W3213888716,This paper investigates how firms can enjoy a ...
17,dynamic pricing definition concepts brick-and-...,Factors Affecting Customer Loyalty of Using In...,2010,article,Journal of Electronic Banking Systems,113,Beh Yee; Tengku Mohamed Faziharudean,https://doi.org/10.5171/2010.592297,https://openalex.org/W2328466805,Internet banking (IB) has become one of the wi...
18,dynamic pricing definition concepts brick-and-...,A SCALE OF CONSUMER ENGAGEMENT,2009,dissertation,W. S. Hoole Special Collections Library Manusc...,130,Shiri D. Vivek,None,https://openalex.org/W2107361737,The practitioner literature is replete with ex...
19,dynamic pricing definition concepts brick-and-...,Examining the anatomy of last-mile distributio...,2018,article,International Journal of Operations & Producti...,82,Stanley Frederick W.T. Lim; Jagjit Singh Srai,https://doi.org/10.1108/ijopm-12-2016-0733,https://openalex.org/W2785998606,Purpose The purpose of this paper is to invest...
20,dynamic pricing definition concepts brick-and-...,International business in the digital age: Glo...,2023,editorial,Journal of International Business Studies,160,Klaus E. Meyer; Jiatao Li; Keith D. Brouthers;...,https://doi.org/10.1057/s41267-023-00618-x,https://openalex.org/W4362554094,None
21,dynamic pricing definition concepts brick-and-...,Shopping as a “networked experience”: an emerg...,2018,article,International Journal of Retail & Distribution...,69,Eleonora Pantano; Alessandro Gandini,https://doi.org/10.1108/ijrdm-01-2018-0024,https://openalex.org/W2887430659,Purpose The purpose of this paper is to devise...
22,dynamic pricing definition concepts brick-and-...,Omnichannel Business,2022,article,Electronic Markets,55,Christiane Lehrer; Manuel Trenz,https://doi.org/10.1007/s12525-021-00511-1,https://openalex.org/W4205284674,None
23,dynamic pricing definition concepts brick-and-...,Competition and antitrust in Internet markets,2016,book-chapter,Edward Elgar Publishing eBooks,65,Justus Haucap; Torben Stühmeier,https://doi.org/10.4337/9780857939852.00017,https://openalex.org/W2189161602,"The rapid rise, enduring growth and success of..."
24,dynamic pricing definition concepts brick-and-...,The phygital transformation: a systematic revi...,2023,review,Italian Journal of Marketing,56,Cristina Mele; Tiziana Russo Spena; Marialuiza...,https://doi.org/10.1007/s43039-023-00070-7,https://openalex.org/W4353033342,Abstract The label “phygital” (physical plus d...
25,dynamic pricing definition concepts brick-and-...,Omni-channel integration: the matter of inform...,2021,article,International Journal of Operations & Producti...,53,Soroosh Saghiri; Vahid Mirzabeiki,https://doi.org/10.1108/ijopm-04-2021-0262,https://openalex.org/W3204283214,Purpose This paper aims to explore how omni-ch...
26,dynamic pricing definition concepts brick-and-...,Innovative or Not? The Effects of Consumer Per...,2021,article,Sustainability,84,Li Zhao; Shujin Shu; Jun Shao; Elizabeth Booth...,https://doi.org/10.3390/su13042412,https://openalex.org/W3129643409,A museum’s core activities traditionally focus...
27,dynamic pricing definition concepts brick-and-...,On the Depth and Dynamics of Online Search Beh...,2004,article,Management Science,65,Eric J. Johnson; Wendy W. Moe; Peter S. Fader;...,https://doi.org/10.1287/mnsc.1040.0194,https://openalex.org/W2136796187,This paper examines search across competing e-...
28,dynamic pricing definition concepts brick-and-...,The challenge of remanufactured products: the ...,2021,article,International Journal of Physical Distribution...,42,Ilenia Confente; Ivan Russo; Simone T. Peinkof...,https://doi.org/10.1108/ijpdlm-03-2020-0089,https://openalex.org/W3152369300,Purpose While remanufactured products represen...
29,dynamic pricing definition concepts brick-and-...,The Sharing Economy as an Urban Phenomenon,2016,article,Yale Law School Legal Scholarship Repository,101,Nestor M. Davidson; John Infranca,None,https://openalex.org/W2992974692,Need a cab? Chances are you’ll click your Uber...
30,dynamic pricing definition concepts brick-and-...,Consumer Experience and Omnichannel Behavior i...,2020,article,Frontiers in Psychology,37,María Dolores Reina Paz; Fernando Jiménez Delgado,https://doi.org/10.3389/fpsyg.2020.01972,https://openalex.org/W3048185176,The conceptual framework for our analysis is t...
31,dynamic pricing definition concepts brick-and-...,Selling luxury products online : the effect of...,2018,article,Ghent University Academic Bibliography (Ghent ...,63,Shubin Yu; Liselot Hudders; Veroline Cauberghe,None,https://openalex.org/W2944285864,Many luxury brands and online retailers are st...
32,dynamic pricing definition concepts brick-and-...,Customer experience dimensions in last-mile de...,2022,article,International Journal of Physical Distribution...,50,John Olsson; Daniel Hellström; Yulia Vakulenko,https://doi.org/10.1108/ijpdlm-12-2021-0517,https://openalex.org/W4297369831,Purpose The success of last-mile delivery is d...
33,dynamic pricing definition concepts brick-and-...,How smart technology empowers consumers in sma...,2023,article,Electronic Markets,41,Jiahe Chen; Yu‐Wei Chang,https://doi.org/10.1007/s12525-023-00635-6,https://openalex.org/W4362577878,None
34,dynamic pricing definition concepts brick-and-...,Internet marketing: a content analysis of the ...,2013,article,Electronic Markets,54,J. Ken Corley; Zack Jourdan; W. Rhea Ingram,https://doi.org/10.1007/s12525-012-0118-y,https://openalex.org/W2097108980,Abstract The amount of research related to Int...
35,dynamic pricing definition concepts brick-and-...,"Information Technology, Cross-Channel Capabili...",2016,article,Journal of the Association for Information Sys...,65,Jifeng Luo; Ming Fan; Han Zhang,https://doi.org/10.17705/1jais.00429,https://openalex.org/W3122249463,Information technology (IT) has changed the dy...
36,dynamic pricing definition concepts brick-and-...,Customer Loyalty Explained by Electronic Recov...,2011,article,Contemporary Management Research,46,Kuang‐Wen Wu,https://doi.org/10.7903/cmr.1101,https://openalex.org/W1897937733,"This non-experimental, causal study related to..."
37,dynamic pricing definition concepts brick-and-...,Website Appeal: Development of an Assessment T...,2014,article,Journal of theoretical and applied electronic ...,53,Salam Abdallah; Bushra Jaleel,https://doi.org/10.4067/s0718-18762015000300005,https://openalex.org/W2156427936,"""The aim of this study is twofold; firstly, to..."
38,dynamic pricing definition concepts brick-and-...,Consumer-driven e-commerce,2018,article,Apollo (University of Cambridge),28,Stanley Frederick W.T. Lim; Xin Jin; Jagjit Si...,https://doi.org/10.17863/cam.22286,https://openalex.org/W3121456441,Purpose The purpose of this paper is to re-exa...
39,dynamic pricing definition concepts brick-and-...,Creating memorable shopping experiences to mee...,2023,article,International Journal of Retail & Distribution...,36,Angelo Bonfanti; Vania Vigolo; Virginia Vannuc...,https://doi.org/10.1108/ijrdm-12-2021-0588,https://openalex.org/W4382894779,Purpose This study focuses on memorable custom...
40,dynamic pricing definition concepts brick-and-...,Purchase intention in an electronic commerce e...,2018,article,Information Technology and People,62,Mahmud Akhter Shareef; Yogesh K. Dwivedi; Vino...,https://doi.org/10.1108/itp-05-2018-0241,https://openalex.org/W2913491028,Purpose The purpose of this paper is to unders...
41,dynamic pricing definition concepts brick-and-...,Landlords with no lands: a systematic literatu...,2021,article,European Journal of Innovation Management,64,Daniel Trabucchi; Tommaso Buganza,https://doi.org/10.1108/ejim-11-2020-0467,https://openalex.org/W3135250694,Purpose This article is based on a systematic ...
42,dynamic pricing definition concepts brick-and-...,Understanding the Continuance Intention of Omn...,2023,article,Sustainability,40,Hyo Geun Song; Hyeon Jo,https://doi.org/10.3390/su15043039,https://openalex.org/W4319599499,"Nowadays, consumers use information devices to..."
43,dynamic pricing definition concepts brick-and-...,Competition in Pricing Algorithms,2021,preprint,None,39,Zach Y. Brown; Alexander MacKay,https://doi.org/10.3386/w28860,https://openalex.org/W3172201168,We document new facts about pricing technology...
44,dynamic pricing definition concepts brick-and-...,WeChat mobile-payment-based smart retail custo...,2021,article,Information Technology and Management,36,Yinglu Sun; Wei Xue; Subir Bandyopadhyay; Dong...,https://doi.org/10.1007/s10799-021-00346-4,https://openalex.org/W3209600469,Abstract The purpose of this paper is to explo...
45,dynamic pricing definition concepts brick-and-...,Understanding freehand gestures: a study of fr...,2019,article,Human-centric Computing and Information Sciences,51,Huiyue Wu; Weizhou Luo; Neng Pan; Shenghuan Na...,https://doi.org/10.1186/s13673-019-0204-7,https://openalex.org/W2992306147,"Abstract Unlike retail stores, in which the us..."
46,dynamic pricing definition concepts brick-and-...,Embracing the E-commerce Revolution in Asia an...,2018,report,None,37,Asian Development Bank,https://doi.org/10.22617/tcs189409-2,https://openalex.org/W4249652048,None
47,dynamic pricing definition concepts brick-and-...,Strategies and practices to reduce the ecologi...,2023,article,Business Strategy and the Environment,36,Danni Zhang; Regina Frei; Gary Wills; Enrico G...,https://doi.org/10.1002/bse.3385,https://openalex.org/W4322500966,Abstract Product returns in retail are inheren...
48,dynamic pricing definition concepts brick-and-...,Dynamic demand management and online tour plan...,2022,article,European Journal of Operational Research,36,Vienna Klein; Claudius Steinhardt,https://doi.org/10.1016/j.ejor.2022.09.011,https://openalex.org/W4295647722,For providers to stay competitive in a context...
49,dynamic pricing definition concepts brick-and-...,Energy Consumption and Environmental Impact of...,2022,article,Energies,22,Soukaina Aziz; Ila Maltese; Edoardo Marcucci; ...,https://doi.org/10.3390/en15197289,https://openalex.org/W4303700016,E-grocery is fast growing worldwide and repres...

# Semantic Scholar (Graph API) — relevance-ranked paper search

In [3]:
import os
import re
import json
import time
import random
import hashlib
from pathlib import Path
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List, Optional, Iterable

import requests
import pandas as pd


# =============================
# USER CONFIG
# =============================
# Your existing list
QUERY_LIST = QUERY_LIST

API_KEY = os.getenv("S2_API_KEY", "").strip()  # recommended but optional

BASE = "https://api.semanticscholar.org/graph/v1"
SEARCH_URL = f"{BASE}/paper/search"          # relevance search (what you used originally)
BATCH_URL  = f"{BASE}/paper/batch"

# Performance toggles
FETCH_ABSTRACTS_VIA_BATCH = True   # search = light fields, then batch fetch abstracts
CACHE_ENABLED = True
CACHE_TTL_DAYS = 30

# How many results per query (relevance search supports offset+limit; limit typically <=100)
LIMIT = 100
MAX_PAGES_PER_QUERY = 1            # set to 2..10 if you want more than 100/query (up to 1000 total results)

# Batch details (paper/batch supports many IDs per call; 200 is safe)
BATCH_SIZE = 200

SAVE_CSV_PATH = "semantic_scholar_results.csv"


# =============================
# Fields (big speed win)
# =============================
# Keep search light (no abstract)
SEARCH_FIELDS = "paperId,title,year,authors,venue,citationCount,externalIds,url"
# Fetch abstract later
DETAIL_FIELDS = "paperId,abstract"


# =============================
# Session
# =============================
session = requests.Session()
session.headers.update({"User-Agent": "s2-relevance-fast/0.6"})
if API_KEY:
    session.headers.update({"x-api-key": API_KEY})

print(
    "Using API key:", bool(API_KEY),
    "| x-api-key header present:", "x-api-key" in session.headers,
    "| key length:", len(session.headers.get("x-api-key", "")),
)


# =============================
# Cache helpers
# =============================
CACHE_DIR = Path(".s2_cache")
CACHE_DIR.mkdir(exist_ok=True)

def _now_utc() -> datetime:
    return datetime.now(timezone.utc)

def _cache_key(method: str, url: str, params: Optional[Dict[str, Any]], body: Optional[Dict[str, Any]]) -> str:
    blob = {"m": method.upper(), "u": url, "p": params or {}, "b": body or {}}
    s = json.dumps(blob, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha1(s).hexdigest()

def cache_get(method: str, url: str, params: Optional[Dict[str, Any]], body: Optional[Dict[str, Any]]) -> Optional[Any]:
    if not CACHE_ENABLED:
        return None
    key = _cache_key(method, url, params, body)
    path = CACHE_DIR / f"{key}.json"
    if not path.exists():
        return None
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
        created = datetime.fromisoformat(payload["created"])
        if _now_utc() - created > timedelta(days=CACHE_TTL_DAYS):
            return None
        return payload["data"]
    except Exception:
        return None

def cache_set(method: str, url: str, params: Optional[Dict[str, Any]], body: Optional[Dict[str, Any]], data: Any) -> None:
    if not CACHE_ENABLED:
        return
    key = _cache_key(method, url, params, body)
    path = CACHE_DIR / f"{key}.json"
    payload = {"created": _now_utc().isoformat(), "data": data}
    path.write_text(json.dumps(payload), encoding="utf-8")


# =============================
# Adaptive pacer (reliable without wasting time)
# =============================
class Pacer:
    def __init__(self):
        # unauth traffic tends to get throttled more; start slower if no key
        self.min_interval = 1.05 if API_KEY else 2.5
        self.max_interval = 30.0
        self.interval = self.min_interval
        self.next_time = 0.0
        self.ok_streak = 0

    def wait(self):
        now = time.monotonic()
        if now < self.next_time:
            time.sleep(self.next_time - now)

    def _schedule(self, extra_wait: float = 0.0):
        self.next_time = time.monotonic() + self.interval + extra_wait + random.random() * 0.15

    def on_200(self):
        self.ok_streak += 1
        factor = 0.90 if self.ok_streak < 3 else 0.80
        self.interval = max(self.min_interval, self.interval * factor)
        self._schedule()

    def on_429(self, retry_after: Optional[float]):
        self.ok_streak = 0
        self.interval = min(self.max_interval, max(self.min_interval, self.interval * 1.5))
        self._schedule(extra_wait=retry_after or 0.0)

    def on_5xx(self, retry_after: Optional[float]):
        self.ok_streak = 0
        self.interval = min(self.max_interval, max(self.min_interval, self.interval * 1.2))
        self._schedule(extra_wait=retry_after or 0.0)

pacer = Pacer()

def _short_body(resp: requests.Response, n: int = 220) -> str:
    txt = (resp.text or "").strip().replace("\n", " ")
    return (txt[:n] + "…") if len(txt) > n else txt

def _parse_retry_after(resp: requests.Response) -> Optional[float]:
    ra = resp.headers.get("Retry-After")
    if not ra:
        return None
    try:
        return float(ra)
    except ValueError:
        return None


# =============================
# Request wrapper
# =============================
def request_json(method: str, url: str, params: Optional[Dict[str, Any]] = None,
                 body: Optional[Dict[str, Any]] = None, max_retries: int = 50, verbose: bool = True) -> Any:
    cached = cache_get(method, url, params, body)
    if cached is not None:
        if verbose:
            print(f"  🧠 cache hit: {method} {url}")
        return cached

    for attempt in range(1, max_retries + 1):
        pacer.wait()
        if verbose:
            print(f"  [S2] {method} attempt {attempt}/{max_retries} | pacer_interval={pacer.interval:.2f}s")

        try:
            resp = session.request(method, url, params=params, json=body, timeout=30)
        except requests.RequestException as e:
            extra = min(10.0, 0.5 * (2 ** (attempt - 1))) + random.random() * 0.25
            if verbose:
                print(f"    ↪ network error: {e} | extra wait {extra:.2f}s")
            pacer._schedule(extra_wait=extra)
            continue

        if verbose:
            print(f"    ↩ status={resp.status_code} | Retry-After={resp.headers.get('Retry-After')}")

        if resp.status_code == 200:
            pacer.on_200()
            data = resp.json()
            cache_set(method, url, params, body, data)
            return data

        retry_after = _parse_retry_after(resp)

        if resp.status_code == 429:
            if verbose:
                print(f"    ⚠️ 429 throttled | body: {_short_body(resp)}")
            pacer.on_429(retry_after)
            continue

        if resp.status_code in (500, 502, 503, 504):
            if verbose:
                print(f"    ⚠️ {resp.status_code} transient | body: {_short_body(resp)}")
            pacer.on_5xx(retry_after)
            continue

        if verbose:
            print(f"    ❌ non-retryable {resp.status_code} | body: {_short_body(resp, 500)}")
        resp.raise_for_status()

    raise RuntimeError(f"Giving up after {max_retries} retries: {method} {url}")


# =============================
# Utilities
# =============================
def clean_query(q: str) -> str:
    q = q.replace("-", " ")
    q = re.sub(r"\s+", " ", q).strip()
    return q

def chunked(xs: List[str], n: int) -> Iterable[List[str]]:
    for i in range(0, len(xs), n):
        yield xs[i:i + n]


# =============================
# Pipeline
# =============================
rows: List[Dict[str, Any]] = []

for qi, q in enumerate(QUERY_LIST, start=1):
    q2 = clean_query(q)
    print(f"\n=== ({qi}/{len(QUERY_LIST)}) RELEVANCE SEARCH: {q2!r} ===")

    offset = 0
    for page in range(1, MAX_PAGES_PER_QUERY + 1):
        params = {
            "query": q2,
            "fields": SEARCH_FIELDS,
            "limit": LIMIT,
            "offset": offset,
        }

        data = request_json("GET", SEARCH_URL, params=params, body=None, max_retries=50, verbose=True)
        papers = data.get("data", []) or []
        print(f"→ page {page}: got {len(papers)} papers")

        for p in papers:
            authors = [a.get("name") for a in (p.get("authors") or [])[:6] if a.get("name")]
            ext = p.get("externalIds") or {}
            rows.append({
                "query": q,
                "paperId": p.get("paperId"),
                "title": p.get("title"),
                "year": p.get("year"),
                "venue": p.get("venue"),
                "citationCount": p.get("citationCount"),
                "authors(first6)": "; ".join(authors),
                "doi": ext.get("DOI"),
                "s2_url": p.get("url"),
                # abstract later
            })

        if len(papers) < LIMIT:
            break
        offset += LIMIT


df = pd.DataFrame(rows)

# Dedup within query+paperId (keeps overlaps across different queries)
df = df.drop_duplicates(subset=["query", "paperId"]).reset_index(drop=True)

# Batch fetch abstracts after dedupe
if FETCH_ABSTRACTS_VIA_BATCH :
    unique_ids = [pid for pid in df["paperId"].dropna().unique().tolist() if pid]
    print(f"\n=== BATCH ABSTRACTS: {len(unique_ids)} unique ids ===")

    abstracts: Dict[str, Optional[str]] = {}

    for bi, ids in enumerate(chunked(unique_ids, BATCH_SIZE), start=1):
        print(f"--- batch {bi} | size={len(ids)} ---")
        params = {"fields": DETAIL_FIELDS}
        body = {"ids": ids}
        batch = request_json("POST", BATCH_URL, params=params, body=body, max_retries=50, verbose=True)

        if isinstance(batch, list):
            for p in batch:
                pid = p.get("paperId")
                if pid:
                    abstracts[pid] = p.get("abstract")
        else:
            for p in (batch.get("data", []) or []):
                pid = p.get("paperId")
                if pid:
                    abstracts[pid] = p.get("abstract")

    df["abstract"] = df["paperId"].map(abstracts)

# Final dedupe (don’t accidentally collapse across queries)
df = df.drop_duplicates(subset=["query", "paperId"]).reset_index(drop=True)

df.to_csv(SAVE_CSV_PATH, index=False)
print(f"\nDone. Rows: {len(df)} | Unique papers: {df['paperId'].nunique()}")
print(f"Saved: {SAVE_CSV_PATH}")

df.head(50)

Using API key: False | x-api-key header present: False | key length: 0

=== (1/6) RELEVANCE SEARCH: 'dynamic pricing definition concepts brick and mortar retail in store offline retail' ===
  🧠 cache hit: GET https://api.semanticscholar.org/graph/v1/paper/search
→ page 1: got 0 papers

=== (2/6) RELEVANCE SEARCH: 'dynamic pricing theory conceptual framework retail' ===
  🧠 cache hit: GET https://api.semanticscholar.org/graph/v1/paper/search
→ page 1: got 100 papers

=== (3/6) RELEVANCE SEARCH: 'time based pricing time dependent pricing dynamic pricing retail store' ===
  🧠 cache hit: GET https://api.semanticscholar.org/graph/v1/paper/search
→ page 1: got 100 papers

=== (4/6) RELEVANCE SEARCH: 'demand based pricing demand driven pricing dynamic pricing retail store' ===
  🧠 cache hit: GET https://api.semanticscholar.org/graph/v1/paper/search
→ page 1: got 100 papers

=== (5/6) RELEVANCE SEARCH: 'revenue management pricing retail dynamic pricing in store' ===
  🧠 cache hit: GET https://api.semanticscholar.org/graph/v1/paper/search
→ page 1: got 100 papers

=== (6/6) RELEVANCE SEARCH: 'price discrimination dynamic pricing retail store' ===
  🧠 cache hit: GET https://api.semanticscholar.org/graph/v1/paper/search
→ page 1: got 100 papers

=== BATCH ABSTRACTS: 422 unique ids ===
--- batch 1 | size=200 ---
  🧠 cache hit: POST https://api.semanticscholar.org/graph/v1/paper/batch
--- batch 2 | size=200 ---
  🧠 cache hit: POST https://api.semanticscholar.org/graph/v1/paper/batch
--- batch 3 | size=22 ---
  🧠 cache hit: POST https://api.semanticscholar.org/graph/v1/paper/batch

Done. Rows: 500 | Unique papers: 422
Saved: semantic_scholar_results.csv

,query,paperId,title,year,venue,citationCount,authors(first6),doi,s2_url,abstract
0,dynamic pricing theory conceptual framework re...,10b032f405418862ee6cbabac505542398709ffa,Dynamic Retail Pricing via Q-Learning - A Rein...,2025.0,2025 1st International Conference on AIML-Appl...,12,Mohit Apte; rd Pranav Datar; Ketan Kale; Dr P....,10.1109/ICAET63349.2025.10932302,https://www.semanticscholar.org/paper/10b032f4...,This study examines how a reinforcement learni...
1,dynamic pricing theory conceptual framework re...,9301266dbebcb2037adf55f09afbd3ad2106d742,Advanced Deep Reinforcement Learning Framework...,2024.0,International Conference on Computing Communic...,2,Anurag Agnihotri; I. Raj,10.1109/ICCCNT61001.2024.10725071,https://www.semanticscholar.org/paper/9301266d...,Pricing transparency is essential in online co...
2,dynamic pricing theory conceptual framework re...,82e42f51ff83bc1fa1a53025c4834dc68457470c,Reforming the innovation system to deliver aff...,2025.0,Journal of Pharmaceutical Policy and Practice,3,Suerie Moon; Adrian Alonso Ruiz; Marcela Vieir...,10.1080/20523211.2024.2436899,https://www.semanticscholar.org/paper/82e42f51...,ABSTRACT Background The current mainstream pha...
3,dynamic pricing theory conceptual framework re...,7a145bbcab2586e0a0b9681524056cf3e96c7669,Joint Optimization of Dynamic Pricing and Peri...,2025.0,2025 International Conference on Artificial In...,2,Anmol Aggarwal; Uttam Kumar; Sai Rakesh Reddy ...,10.1109/AIMV66517.2025.11203504,https://www.semanticscholar.org/paper/7a145bbc...,"Perishable goods, such as fresh produce or dai..."
4,dynamic pricing theory conceptual framework re...,4436d58d863c78ae2d04956b812fd2eb996e4fa9,A conceptual model for automation of product d...,2016.0,Kybernetes,4,Anup Kumar,10.1108/K-03-2015-0075,https://www.semanticscholar.org/paper/4436d58d...,None
5,dynamic pricing theory conceptual framework re...,0d2c7ed8ce1191e2507f3b10615b6174cffc5a38,Continuous dynamic pricing strategy under comp...,2024.0,Sādhanā,2,Anand Ranjan; J. K. Jha,10.1007/s12046-024-02468-1,https://www.semanticscholar.org/paper/0d2c7ed8...,None
6,dynamic pricing theory conceptual framework re...,d7953adedf4866a2a1142201aefce2f9557f6cd4,Dynamic Capabilities and MNE Global Strategy: ...,2023.0,Journal of Management Studies,74,Christos N. Pitelis; D. Teece; Hongyi Yang,10.1111/joms.13021,https://www.semanticscholar.org/paper/d7953ade...,Global strategy cannot be fully understood wit...
7,dynamic pricing theory conceptual framework re...,25617f1922f7f1f91ef235afa7b9f3c35b3a2f6a,Real Time Sales Forecasting in Omnichannel Ret...,2025.0,Academic Journal of Sociology and Management,3,Huanyu Liu; Tian Qi,10.70393/616a736d.323932,https://www.semanticscholar.org/paper/25617f19...,"In an omnichannel retail environment, accurate..."
8,dynamic pricing theory conceptual framework re...,bcdc65d4940486c2ec5b222d32b474f9de9b542c,Toward Dynamic Pricing for City-Wide Crowdsour...,2024.0,IEEE Transactions on Mobile Computing,5,Sen Bai; S. Tong; Xin Feng; Zhengang Jiang; Xi...,10.1109/TMC.2022.3228259,https://www.semanticscholar.org/paper/bcdc65d4...,The booming crowdsourced delivery leverages ne...
9,dynamic pricing theory conceptual framework re...,ccb8b9c457640cc3c5a51cb5c88e1ceb798488c2,Online Product Reviews-Triggered Dynamic Prici...,2019.0,Information systems research,89,Juan Feng; Xin Li; X. Zhang,10.1287/ISRE.2019.0852,https://www.semanticscholar.org/paper/ccb8b9c4...,Prior works offer compelling evidence that on ...
10,dynamic pricing theory conceptual framework re...,1423e808355db6cb4d48bf06c6c83b6a784aca33,Machine Learning Algorithms for Dynamic Pricin...,2025.0,Social Science Research Network,2,Ravikumar Perumallaplli,10.2139/ssrn.5228515,https://www.semanticscholar.org/paper/1423e808...,"In the retail industry, dynamic pricing has be..."
11,dynamic pricing theory conceptual framework re...,24dd29fac417a4a72d0aeac67e1b028a9d80aca3,Pricing Models for 5G Multi-Tenancy Using Game...,2024.0,IEEE Communications Magazine,7,Shruthi Koratagere Anantha Kumar; David H. Cra...,10.1109/MCOM.001.2200742,https://www.semanticscholar.org/paper/24dd29fa...,Regions with little or no access to modern inf...
12,dynamic pricing theory conceptual framework re...,cc5583cf3ee38a2366277e2e85981f7060630185,Dynamic Collaborative Pricing for Managing Ref...,2024.0,IEEE Transactions on Transportation Electrific...,23,Zhixue Yang; Hui Li; Hongcai Zhang,10.1109/TTE.2024.3381236,https://www.semanticscholar.org/paper/cc5583cf...,Green hydrogen from renewable energy is a prom...
13,dynamic pricing theory conceptual framework re...,6f8bef93e09093bf17bd71d600fe609f057d8ffd,Legal Infrastructures: Towards a Conceptual Fr...,2024.0,German Law Journal,3,W. H. Byrne; Thomas Gammeltoft-Hansen; Nora St...,10.1017/glj.2024.78,https://www.semanticscholar.org/paper/6f8bef93...,Abstract This Article provides the outline for...
14,dynamic pricing theory conceptual framework re...,8c4f5b961f7553900ff4d2fc745b4f7eedeb7e72,A conceptual framework for Emergent Language L...,2024.0,Innovation in Language Learning and Teaching,5,Thomas Stringer,10.1080/17501229.2024.2371505,https://www.semanticscholar.org/paper/8c4f5b96...,ABSTRACT Purpose This paper addresses inconsis...
15,dynamic pricing theory conceptual framework re...,d81b0ba3c5578a68fc8ac0de7d678b5a8b1624fb,The Digital-Sustainability Ecosystem: A concep...,2025.0,"Journal of Entrepreneurship, Management and In...",15,Anna Florek-Paszkowska; A. Ujwary-Gil,10.7341/20252127,https://www.semanticscholar.org/paper/d81b0ba3...,PURPOSE: This study introduces the Digital-Sus...
16,dynamic pricing theory conceptual framework re...,0d341b73601ac752f5942e3edf1dc1981e119ebc,An Omnichannel Retailing Operation for Solving...,2023.0,IEEE Access,6,Guitao Xu; Kai Kang; Mengyao Lu,10.1109/ACCESS.2023.3244400,https://www.semanticscholar.org/paper/0d341b73...,"Customer experience, a key element in the doma..."
17,dynamic pricing theory conceptual framework re...,baae3e8b912b0c2c423c0c888533bd1c37fc3d44,Dynamic capabilities for the creation of logis...,2021.0,,30,E. Sandberg,10.1108/IJLM-07-2020-0266,https://www.semanticscholar.org/paper/baae3e8b...,PurposeThe purpose of this research is to deve...
18,dynamic pricing theory conceptual framework re...,f23cfd45d65e1be0dd345ffd3644353a8a7d936f,Supermarkets in Cyberspace: A Conceptual Frame...,2020.0,International Journal of Environmental Researc...,38,Neha Khandpur; Laura Y Zatz; S. Bleich; L. S. ...,10.3390/ijerph17228639,https://www.semanticscholar.org/paper/f23cfd45...,The rapid increase in online shopping and the ...
19,dynamic pricing theory conceptual framework re...,a771462ac3a3b44244eb2a96b78d83efdf870336,Consumer Intention towards Webrooming Behavior...,2022.0,Sustainable Business and Society in Emerging E...,3,Sarah Zafar; Rana Muhammad Shahid Yaqub,10.26710/sbsee.v4i2.2389,https://www.semanticscholar.org/paper/a771462a...,Purpose: Recent research about consumer webroo...
20,dynamic pricing theory conceptual framework re...,dfcfd4af600e30e7e8c3f155f2f49d46087e6609,Capacity building for organizational performan...,2024.0,Cogent Business &amp; Management,29,Nika Saputra; Roni Ekha Putera; Aidinil Zetra;...,10.1080/23311975.2024.2434966,https://www.semanticscholar.org/paper/dfcfd4af...,Abstract This study presents a comprehensive r...
21,dynamic pricing theory conceptual framework re...,a76c978d76add6cab8b3ef8c480bc8c671964c8e,The Optimal Pricing Models: Dynamic Pricing Pe...,2024.0,BigData Congress [Services Society],2,Kazuhiro Miyatsu,10.1109/BigData62323.2024.10825186,https://www.semanticscholar.org/paper/a76c978d...,"In the field of marketing, the framework known..."
22,dynamic pricing theory conceptual framework re...,7b1f346cd12ff79e2dcceedf6816a3308a1508a1,Bridging principal-agent and mechanism design ...,2023.0,Asia Pacific Education Review,6,Heeyun Kim,10.1007/s12564-023-09844-2,https://www.semanticscholar.org/paper/7b1f346c...,None
23,dynamic pricing theory conceptual framework re...,4230e841e90b8a61cc39e963983fb69502bce22e,Tourist walkability and sustainable community-...,2023.0,International Journal of Tourism Cities,7,P. Yeap; M. Liow,10.1108/ijtc-05-2022-0117,https://www.semanticscholar.org/paper/4230e841...,\nPurpose\nThis paper aims to determine the si...
24,dynamic pricing theory conceptual framework re...,885a7395b5b65ea443145dea78552b0649c50396,Dynamic pricing in the presence of reference p...,2020.0,International Journal of Production Research,96,Kehong Chen; Yong Zha; Layth C. Alwan; Lu Zhang,10.1080/00207543.2019.1598592,https://www.semanticscholar.org/paper/885a7395...,This paper presents a model for designing two-...
25,dynamic pricing theory conceptual framework re...,2a77554f05bc265cd49ab4bdf06be55a9cbf665f,Reflections on developing a conceptual framewo...,2019.0,Nurse Researcher,4,Collette Straughair,10.7748/nr.2019.e1621,https://www.semanticscholar.org/paper/2a77554f...,BACKGROUND\nDeveloping a conceptual framework ...
26,dynamic pricing theory conceptual framework re...,07107cdf6f87bed24acf273d9c23de4b8fd0e24f,Dynamic Pricing Mechanism With the Integration...,2020.0,IEEE Access,53,M. B. Rasheed; M. A. Qureshi; N. Javaid; T. Al...,10.1109/ACCESS.2020.2967798,https://www.semanticscholar.org/paper/07107cdf...,Day-ahead electricity pricing is an important ...
27,dynamic pricing theory conceptual framework re...,edf30298d6c89a3773a873c2e461bce10b6788f4,Dynamic Pricing; A Bibliometric Approach,2021.0,,5,,10.22059/IJMS.2021.315212.674336,https://www.semanticscholar.org/paper/edf30298...,None
28,dynamic pricing theory conceptual framework re...,0049d19e5408aca5fb1b86686f327469575a6719,Conceptual and strategic framework for the dig...,2020.0,E3S Web of Conferences,20,I. Krasyuk; M. Yanenko; E. Nazarova,10.1051/e3sconf/202016409006,https://www.semanticscholar.org/paper/0049d19e...,Change of a market situation causes necessity ...
29,dynamic pricing theory conceptual framework re...,6b74b883432e8169d1e88e8c4b80e6b5e90af3f2,Toward an Ecologically Valid Conceptual Framew...,2022.0,JMIR Human Factors,33,Avishek Choudhury,10.2196/35421,https://www.semanticscholar.org/paper/6b74b883...,The health care management and the medical pra...
30,dynamic pricing theory conceptual framework re...,bc01fb8112b3ea4eff03f4c9fabad212f76c3c67,An IS-Perspective on Omni-channel Management: ...,2018.0,European Conference on Information Systems,8,Benjamin Barann,None,https://www.semanticscholar.org/paper/bc01fb81...,None
31,dynamic pricing theory conceptual framework re...,d926c45974a19b6acc061efd0e9f6bee5590233a,Framework for adoption of generative AI for in...,2024.0,International Journal of Retail &amp; Distribu...,23,A. Gupta; Jaydeep Mukherjee,10.1108/ijrdm-05-2024-0203,https://www.semanticscholar.org/paper/d926c459...,PurposeGenerative artificial intelligence (GAI...
32,dynamic pricing theory conceptual framework re...,6aa7107fc7b2f121890434f6012d690277763c7b,Empirical studies in online retail operations ...,2016.0,,2,Jiaqi Xu,None,https://www.semanticscholar.org/paper/6aa7107f...,None
33,dynamic pricing theory conceptual framework re...,83eaf8951ce74b51bca46482b70b4339e1e8d5a5,Music performance as knowledge acquisition: a ...,2024.0,Frontiers in Psychology,8,M. Reybrouck; A. Schiavio,10.3389/fpsyg.2024.1331806,https://www.semanticscholar.org/paper/83eaf895...,To what extent does playing a musical instrume...
34,dynamic pricing theory conceptual framework re...,1850623e3dc871fbfb86f913f897648370fdd2f9,An Axiomatic Framework for Ex-Ante Dynamic Pri...,2016.0,AAAI Conference on Artificial Intelligence,7,S. Bandyopadhyay; Ramasuri Narayanam; Pratyush...,10.1609/aaai.v30i1.9900,https://www.semanticscholar.org/paper/1850623e...,"\n \n In electricity markets, the choice of th..."
35,dynamic pricing theory conceptual framework re...,62c7f4bf087f9af9649bfff159b528210e4b545d,"Financial resilience: a scoping review, concep...",2025.0,International Journal of Bank Marketing,9,Zewei Liu; Ji-kang Chen; Jing Jian Xiao,10.1108/ijbm-12-2024-0735,https://www.semanticscholar.org/paper/62c7f4bf...,PurposeFinancial resilience is becoming increa...
36,dynamic pricing theory conceptual framework re...,471c6e9712a5e2ca4dcc467069744859810f8610,Developing a Conceptual Framework for AI-Drive...,2023.0,International Journal of Multidisciplinary Res...,15,Ajayi Abisoye,10.54660/.ijmrge.2023.4.1.1074-1083,https://www.semanticscholar.org/paper/471c6e97...,"The rapid evolution of science, technology, en..."
37,dynamic pricing theory conceptual framework re...,709546e0a6d15f49b111513d70f9ff8f5492b65a,The Role of Social Facilitation Theory on Cons...,2016.0,,8,,None,https://www.semanticscholar.org/paper/709546e0...,None
38,dynamic pricing theory conceptual framework re...,05dd16a37050a7db3e105cee7b303428bc092843,Understanding Emotion in Physical Education Te...,2021.0,,21,Kelly L. Simonton; K. A. Richards; Nicholas S....,10.1080/00336297.2021.1915352,https://www.semanticscholar.org/paper/05dd16a3...,ABSTRACT While more developed in the general e...
39,dynamic pricing theory conceptual framework re...,e6922de3908d046811a88b589e688019ac03c890,A Conceptual Framework for Integrated Communit...,2021.0,International Journal of Integrated Care,30,Y. Thiam; Jean-François Allaire; P. Morin; She...,10.5334/ijic.5555,https://www.semanticscholar.org/paper/e6922de3...,Introduction: The various health and social ca...
40,dynamic pricing theory conceptual framework re...,969f91d1c0a1dfd94b8d7b19d0d971db1c57b3e4,Overview of Acceptance Islamic Payment Gateway...,2023.0,International Journal of Professional Business...,5,Ahmad Mujahid Mat Rasid; M. Bakri; M. Razak; A...,10.26668/businessreview/2023.v8i5.1351,https://www.semanticscholar.org/paper/969f91d1...,Purpose: The goal of this study is to propose ...
41,dynamic pricing theory conceptual framework re...,fbbb9f40624237f15f9f34d836b620f2cfc93d45,Dynamic conceptual framework to investigate ad...,2021.0,British Food Journal,4,J. Rahmani; J. mirzay razaz; Naser Kalantari; ...,10.1108/BFJ-09-2020-0828,https://www.semanticscholar.org/paper/fbbb9f40...,PurposeThe purpose of this research is to deve...
42,dynamic pricing theory conceptual framework re...,27bd765c940bae00e573dcaf8ead76b072c06a6a,Exploring Relationships Between Family Firms’ ...,2021.0,FIIB Business Review,15,Sanjay Chaudhary; Deepak Sangroya; P. Nema,10.1177/23197145211020724,https://www.semanticscholar.org/paper/27bd765c...,This conceptual article uses dynamic capabilit...
43,dynamic pricing theory conceptual framework re...,f28ce56119a6b830f856fb722952c226fb9abe8f,Towards an ecological-dynamics design framewor...,2020.0,Educational technology research and development,22,Dor Abrahamson; Rotem Abdu,10.1007/s11423-020-09805-1,https://www.semanticscholar.org/paper/f28ce561...,None
44,dynamic pricing theory conceptual framework re...,200650312b46c6a29a3414c64df849e718281195,Retail pricing models,2023.0,Journal of Revenue and Pricing Management,0,I. Yeoman,10.1057/s41272-023-00433-x,https://www.semanticscholar.org/paper/20065031...,None
45,dynamic pricing theory conceptual framework re...,5e703c8eaa0eda3f23a8777bca81b6532b58a0f0,ESG-Valued Portfolio Optimization and Dynamic ...,2022.0,,11,D. Lauria; W. Lindquist; S. Mittnik; S. Rachev,None,https://www.semanticscholar.org/paper/5e703c8e...,ESG ratings provide a quantitative measure for...
46,dynamic pricing theory conceptual framework re...,c50c48bc9b6e3ee0804ae2cadce7f6ed247b0523,A conceptual framework of RFID adoption in ret...,2015.0,Business Process Management Journal,42,Mithu Bhattacharya,10.1108/BPMJ-06-2014-0047,https://www.semanticscholar.org/paper/c50c48bc...,None
47,dynamic pricing theory conceptual framework re...,e3df0ccd2c2a9c90d4eff9fa1c9f7e7faa55c30f,Cumulative Prospect Theory Based Dynamic Prici...,2019.0,IEEE Conference on Decision and Control,20,Yue Guan; A. Annaswamy; H. E. Tseng,10.1109/CDC40024.2019.9029508,https://www.semanticscholar.org/paper/e3df0ccd...,Cumulative Prospect Theory (CPT) is a modeling...
48,dynamic pricing theory conceptual framework re...,61083bf4209666cd4981f512eeb7300ec9ef8f5a,Data-driven sustainability: advancing supply c...,2025.0,Journal of Revenue and Pricing Management,3,Ishita Bera; S. Modgil; A. Shrivastava; Rohit ...,10.1057/s41272-025-00521-0,https://www.semanticscholar.org/paper/61083bf4...,None
49,dynamic pricing theory conceptual framework re...,b3cdc329a8516e4d3ddc6e63b439df64867faf8e,Development of a Conceptual Framework for Mach...,2020.0,Wirtschaftsinformatik,1,J. Becker; K. Müller; Ann-Kristin Cordes; Max ...,10.30844/wi_2020_c2-becker,https://www.semanticscholar.org/paper/b3cdc329...,. The growing prevalence and impact of e-comme...

# Crossref (Works) — DOI-centric metadata across publishers

In [5]:
import requests
import pandas as pd

BASE_URL = "https://api.crossref.org/works"

# Crossref strongly prefers a descriptive User-Agent; include your email.
HEADERS = {
    "User-Agent": "chapter-sources-prototype/0.1 (mailto:your_email@example.com)"
}

rows = []
for q in QUERY_LIST:
    params = {
        "query.bibliographic": q,
        "rows": 100,
        "sort": "relevance",
        "order": "desc",
    }
    r = requests.get(BASE_URL, headers=HEADERS, params=params, timeout=30)
    r.raise_for_status()
    items = (r.json().get("message") or {}).get("items") or []

    for it in items:
        authors = []
        for a in (it.get("author") or [])[:6]:
            name = " ".join([x for x in [a.get("given"), a.get("family")] if x])
            if name:
                authors.append(name)

        title = (it.get("title") or [None])[0]
        year = None
        if it.get("issued", {}).get("date-parts"):
            year = it["issued"]["date-parts"][0][0]

        rows.append({
            "query": q,
            "title": title,
            "year": year,
            "type": it.get("type"),
            "container_title": (it.get("container-title") or [None])[0],
            "authors(first6)": "; ".join(authors),
            "doi": it.get("DOI"),
            "publisher": it.get("publisher"),
        })

df_crossref = pd.DataFrame(rows)
df_crossref = df_crossref.drop_duplicates(subset=["title", "doi"]).reset_index(drop=True)


# List the length of the dataframe
print(f"Total unique works retrieved: {len(df_crossref)}")

df_crossref.head(50)

Total unique works retrieved: 516

,query,title,year,type,container_title,authors(first6),doi,publisher
0,dynamic pricing definition concepts brick-and-...,In-Store Apps,2020.0,book-chapter,Retail Isn't Dead,Matthias Spanke,10.1007/978-3-030-36650-6_10,Springer International Publishing
1,dynamic pricing definition concepts brick-and-...,Saving Brick-and-Mortar Retail: Effects of Con...,2020.0,proceedings-article,Pivoting for the Pandemic,Ji Young Lee; Ki Ho Park,10.31274/itaa.12189,Iowa State University Digital Press
2,dynamic pricing definition concepts brick-and-...,Innovative Retail Retail User Behaviour of Pri...,2024.0,posted-content,None,Lingyao Jin,10.2139/ssrn.4849512,Elsevier BV
3,dynamic pricing definition concepts brick-and-...,On the Welfare Implications of Dynamic Pricing...,2017.0,journal-article,SSRN Electronic Journal,Ioannis Stamatopoulos; Achal Bassamboo,10.2139/ssrn.2927521,Elsevier BV
4,dynamic pricing definition concepts brick-and-...,Retail Isn't Dead,2020.0,book,None,Matthias Spanke,10.1007/978-3-030-36650-6,Springer International Publishing
5,dynamic pricing definition concepts brick-and-...,Saving Brick-and-Mortar Fashion Retail : The I...,2024.0,journal-article,International Journal of Costume and Fashion,Ji Young Lee; Ki Ho Park,10.7233/ijcf.2024.24.1.019,The Korea Society of Costume
6,dynamic pricing definition concepts brick-and-...,Delivery,2020.0,book-chapter,Retail Isn't Dead,Matthias Spanke,10.1007/978-3-030-36650-6_13,Springer International Publishing
7,dynamic pricing definition concepts brick-and-...,Community Hub,2020.0,book-chapter,Retail Isn't Dead,Matthias Spanke,10.1007/978-3-030-36650-6_4,Springer International Publishing
8,dynamic pricing definition concepts brick-and-...,Social Networks,2020.0,book-chapter,Retail Isn't Dead,Matthias Spanke,10.1007/978-3-030-36650-6_9,Springer International Publishing
9,dynamic pricing definition concepts brick-and-...,Virtual Reality,2020.0,book-chapter,Retail Isn't Dead,Matthias Spanke,10.1007/978-3-030-36650-6_6,Springer International Publishing
10,dynamic pricing definition concepts brick-and-...,Paid Experience,2020.0,book-chapter,Retail Isn't Dead,Matthias Spanke,10.1007/978-3-030-36650-6_2,Springer International Publishing
11,dynamic pricing definition concepts brick-and-...,Closing Words,2020.0,book-chapter,Retail Isn't Dead,Matthias Spanke,10.1007/978-3-030-36650-6_16,Springer International Publishing
12,dynamic pricing definition concepts brick-and-...,Augmented Reality,2020.0,book-chapter,Retail Isn't Dead,Matthias Spanke,10.1007/978-3-030-36650-6_5,Springer International Publishing
13,dynamic pricing definition concepts brick-and-...,Easy Checkout,2020.0,book-chapter,Retail Isn't Dead,Matthias Spanke,10.1007/978-3-030-36650-6_11,Springer International Publishing
14,dynamic pricing definition concepts brick-and-...,Artificial Intelligence,2020.0,book-chapter,Retail Isn't Dead,Matthias Spanke,10.1007/978-3-030-36650-6_7,Springer International Publishing
15,dynamic pricing definition concepts brick-and-...,"Rent, Resale, Redesign",2020.0,book-chapter,Retail Isn't Dead,Matthias Spanke,10.1007/978-3-030-36650-6_15,Springer International Publishing
16,dynamic pricing definition concepts brick-and-...,Point of Sale,2020.0,book-chapter,Retail Isn't Dead,Matthias Spanke,10.1007/978-3-030-36650-6_14,Springer International Publishing
17,dynamic pricing definition concepts brick-and-...,Testing and Playing,2020.0,book-chapter,Retail Isn't Dead,Matthias Spanke,10.1007/978-3-030-36650-6_1,Springer International Publishing
18,dynamic pricing definition concepts brick-and-...,Pop-Up Shop,2020.0,book-chapter,Retail Isn't Dead,Matthias Spanke,10.1007/978-3-030-36650-6_3,Springer International Publishing
19,dynamic pricing definition concepts brick-and-...,Pickup and Returns,2020.0,book-chapter,Retail Isn't Dead,Matthias Spanke,10.1007/978-3-030-36650-6_12,Springer International Publishing
20,dynamic pricing definition concepts brick-and-...,Navigating the retail downfall: strategies to ...,2025.0,journal-article,"The International Review of Retail, Distributi...",Jonas Rau; Maria Günther; Andreas Pfnür,10.1080/09593969.2025.2586000,Informa UK Limited
21,dynamic pricing definition concepts brick-and-...,RFID: Radio Frequency Identification,2020.0,book-chapter,Retail Isn't Dead,Matthias Spanke,10.1007/978-3-030-36650-6_8,Springer International Publishing
22,dynamic pricing definition concepts brick-and-...,Understanding consumer repurchase and word-of-...,2025.0,journal-article,South Asian Journal of Marketing,Farhan Mirza; Ding Hooi Ting; Ali Hussain,10.1108/sajm-01-2024-0002,Emerald
23,dynamic pricing definition concepts brick-and-...,Display slot auctions in brick-and-mortar reta...,2025.0,journal-article,Journal of Revenue and Pricing Management,Alejandro Lim; Lanshan Han; Alvin Lim,10.1057/s41272-024-00504-7,Springer Science and Business Media LLC
24,dynamic pricing definition concepts brick-and-...,Weakly Supervised Learning-Based Product Detec...,2024.0,posted-content,None,Jaewoo Song; Dabin Park; daesik jeong; Byungju...,10.2139/ssrn.4719904,Elsevier BV
25,dynamic pricing definition concepts brick-and-...,Dynamic pricing to reduce retail dairy shrink:...,2026.0,posted-content,None,Aaron Adalja; Aljosa Trmcic; Saumya Desai; Leo...,10.2139/ssrn.6051095,Elsevier BV
26,dynamic pricing definition concepts brick-and-...,Dynamic Pricing in Retail Gasoline Markets,1993.0,report,None,Severin Borenstein; Andrea Shepard,10.3386/w4489,National Bureau of Economic Research
27,dynamic pricing definition concepts brick-and-...,Retail store design,2007.0,book-chapter,International Retail Marketing,,10.4324/9780080473123-15,Routledge
28,dynamic pricing definition concepts brick-and-...,Chain-store Pricing and the Structure of Retai...,2006.0,journal-article,SSRN Electronic Journal,Matt Olczak,10.2139/ssrn.912173,Elsevier BV
29,dynamic pricing definition concepts brick-and-...,Chain-store Pricing and the Structure of Retai...,2006.0,journal-article,SSRN Electronic Journal,Matt Olczak,10.2139/ssrn.888532,Elsevier BV
30,dynamic pricing definition concepts brick-and-...,Retail Restructuring and Retail Analysis,2014.0,book-chapter,"Store Choice, Store Location and Market Analys...",,10.4324/9781315736686-10,Routledge
31,dynamic pricing definition concepts brick-and-...,Effectiveness of Consumer Promotions in Brick-...,2022.0,journal-article,CARDIOMETRY,"Dhwanit, K.; Verma, R.; Gandhi, A.",10.18137/cardiometry.2022.24.877886,RosNOU
32,dynamic pricing definition concepts brick-and-...,Digital Transformation in Retail: Strategies f...,2024.0,journal-article,Universal Research Reports,Harsandaldeep Kaur,10.36676/urr.v11.i4.1295,Shodh Sagar
33,dynamic pricing definition concepts brick-and-...,Assessing the moderating effect of brick-and-m...,2022.0,journal-article,International Journal of Retail &amp; Distribu...,Rafael Teixeira; André Luís de Castro Moura Du...,10.1108/ijrdm-03-2021-0139,Emerald
34,dynamic pricing definition concepts brick-and-...,Students’ Perceptions of a Simulated Store Pla...,2022.0,journal-article,Clothing and Textiles Research Journal,Dina Smith-Glaviana; Briana Martinez,10.1177/0887302x221084057,SAGE Publications
35,dynamic pricing definition concepts brick-and-...,Study 2: Retail Branding and Local Competition...,2014.0,book-chapter,Retail Branding and Store Loyalty,Bettina Berg,10.1007/978-3-658-01596-1_3,Springer Fachmedien Wiesbaden
36,dynamic pricing definition concepts brick-and-...,Machine Learning-based Pricing Optimization fo...,2024.0,journal-article,Journal of Informatics Education and Research,,10.52783/jier.v4i3.1564,Science Research Society
37,dynamic pricing definition concepts brick-and-...,Retail positioning and store image 189,2007.0,book-chapter,International Retail Marketing,,10.4324/9780080473123-23,Routledge
38,dynamic pricing definition concepts brick-and-...,Retail Pricing and Repricing of Merchandise,NaN,book-chapter,Mathematics for Retail Buying,,10.5040/9781501315688.ch-002,Fairchild Books
39,dynamic pricing definition concepts brick-and-...,Merging Advantages of Online Shopping with Off...,2022.0,journal-article,SSRN Electronic Journal,Tian Lu; Tingting Song; Xianghua Lu,10.2139/ssrn.4092433,Elsevier BV
40,dynamic pricing definition concepts brick-and-...,"When it rains, it pours? The impact of weather...",2024.0,journal-article,Journal of Retailing and Consumer Services,Jianhao Hu; Xuan Zhang; Hanyu(Yuki) Chen; Wany...,10.1016/j.jretconser.2023.103664,Elsevier BV
41,dynamic pricing definition concepts brick-and-...,Tantangan Dan Peluang Brick And Mortar Retail ...,2016.0,journal-article,Akubis: Jurnal Akuntansi dan Bisnis,Michael Kristanto,10.37832/akubis.v1i01.5,Universitas Katolik Widya Karya Malang
42,dynamic pricing definition concepts brick-and-...,Exclusivity and Expansion into Brick-and-Mortar,2019.0,other,Bloomsbury Fashion Business Cases,Melodie Davis-Bundrage,10.5040/9781350996014.0009,Bloomsbury Publishing Plc
43,dynamic pricing definition concepts brick-and-...,Designing Retail Development Spaces – The Case...,2025.0,proceedings-article,Designing Retail &amp; Services Futures Colloq...,Maximilian Perez Mengual; Frank Danzinger,10.21606/drsf.122,Design Research Society
44,dynamic pricing definition concepts brick-and-...,Review of Intangible Urban Planning Aspects fo...,2021.0,book-chapter,Global Emerging Innovation Summit (GEIS-2021),,10.2174/9781681089010121010042,BENTHAM SCIENCE PUBLISHERS
45,dynamic pricing definition concepts brick-and-...,Reinventing retail the latest Silicon Valley a...,2016.0,journal-article,IEEE Spectrum,Tekl A. S. Perry,10.1109/mspec.2016.7439585,Institute of Electrical and Electronics Engine...
46,dynamic pricing definition concepts brick-and-...,Store Operations and Retail Data,2012.0,other,Retail Analytics,,10.1002/9781119205340.ch6,Wiley
47,dynamic pricing definition concepts brick-and-...,A consumer definition of store convenience (fi...,2014.0,journal-article,International Journal of Retail &amp; Distribu...,Vaughan Reimers,10.1108/ijrdm-03-2013-0060,Emerald
48,dynamic pricing definition concepts brick-and-...,Impact of COVID-19 on Brick-and Mortar Retail ...,2024.0,book-chapter,Pandemic Perspectives,Shweta Paradkar; Monica Rani,10.4324/9781003480297-10,Routledge
49,dynamic pricing definition concepts brick-and-...,Optimal retail pricing of a store brand,2008.0,journal-article,Journal of Product &amp; Brand Management,S. Chan Choi,10.1108/10610420810864711,Emerald

# 4) NCBI E-utilities (PubMed) — likely empty here, but good for biomedical chapters

In [ ]:
import os
import requests
import pandas as pd

NCBI_API_KEY = os.getenv("NCBI_API_KEY", "")  # optional

ESEARCH = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi"
ESUMMARY = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi"

rows = []
for q in QUERY_LIST:
    params = {
        "db": "pubmed",
        "term": q,
        "retmax": 100,
        "retmode": "json",
    }
    if NCBI_API_KEY:
        params["api_key"] = NCBI_API_KEY

    r = requests.get(ESEARCH, params=params, timeout=30)
    r.raise_for_status()
    idlist = (r.json().get("esearchresult") or {}).get("idlist") or []
    if not idlist:
        continue

    params2 = {"db": "pubmed", "id": ",".join(idlist), "retmode": "json"}
    if NCBI_API_KEY:
        params2["api_key"] = NCBI_API_KEY

    r2 = requests.get(ESUMMARY, params=params2, timeout=30)
    r2.raise_for_status()
    result = r2.json().get("result") or {}
    uids = result.get("uids") or []

    for uid in uids:
        rec = result.get(uid) or {}
        authors = [a.get("name") for a in (rec.get("authors") or [])[:6] if a.get("name")]
        rows.append({
            "query": q,
            "pmid": uid,
            "title": rec.get("title"),
            "pubdate": rec.get("pubdate"),
            "source": rec.get("source"),
            "authors(first6)": "; ".join(authors),
        })

df_pubmed = pd.DataFrame(rows)
df_pubmed.head(50)

# arXiv API — preprints

In [ ]:
import requests
import pandas as pd
import xml.etree.ElementTree as ET

BASE_URL = "http://export.arxiv.org/api/query"

def arxiv_search_query(q: str) -> str:
    # arXiv has its own query syntax; keep it simple for now:
    # search all fields for quoted phrase chunks
    # Example: all:"dynamic pricing" AND all:retail
    return f'all:"{q}"'

rows = []
for q in QUERY_LIST:
    params = {
        "search_query": arxiv_search_query(q),
        "start": 0,
        "max_results": 100,
    }
    r = requests.get(BASE_URL, params=params, timeout=30)
    r.raise_for_status()

    root = ET.fromstring(r.text)
    ns = {
        "atom": "http://www.w3.org/2005/Atom",
        "arxiv": "http://arxiv.org/schemas/atom",
    }

    for entry in root.findall("atom:entry", ns):
        title = (entry.findtext("atom:title", default="", namespaces=ns) or "").strip().replace("\n", " ")
        published = entry.findtext("atom:published", default=None, namespaces=ns)
        link = None
        for l in entry.findall("atom:link", ns):
            if l.attrib.get("rel") == "alternate":
                link = l.attrib.get("href")
        authors = [a.findtext("atom:name", default="", namespaces=ns) for a in entry.findall("atom:author", ns)]
        authors = [a for a in authors if a][:6]

        rows.append({
            "query": q,
            "title": title,
            "published": published,
            "authors(first6)": "; ".join(authors),
            "url": link,
        })

df_arxiv = pd.DataFrame(rows).drop_duplicates(subset=["title", "url"]).reset_index(drop=True)
df_arxiv.head(50)

# Open Library (Search API) — books

In [ ]:
import requests
import pandas as pd

BASE_URL = "https://openlibrary.org/search.json"

rows = []
for q in QUERY_LIST:
    params = {"q": q, "limit": 100, "offset": 0}
    r = requests.get(BASE_URL, params=params, timeout=30)
    r.raise_for_status()
    docs = r.json().get("docs") or []

    for d in docs:
        authors = (d.get("author_name") or [])[:6]
        rows.append({
            "query": q,
            "title": d.get("title"),
            "first_publish_year": d.get("first_publish_year"),
            "edition_count": d.get("edition_count"),
            "authors(first6)": "; ".join(authors),
            "openlibrary_key": d.get("key"),
        })

df_openlibrary = pd.DataFrame(rows).drop_duplicates(subset=["title", "openlibrary_key"]).reset_index(drop=True)
df_openlibrary.head(50)